# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

def shared_pods
  pod 'Masonry'
  pod 'PGDatePicker'
  pod 'RTRootNavigationController'
end

target 'EyeProtectionAction' do
  shared_pods
  
end
